cylinders_number: 1
#ALL ANGLES ARE IN DEGREES

cylinders: [
    { radius: 0.3, height: 3.5, x: 0.0, y: 4.0, z: 1.75, roll: 0., pitch: 0.0 },
    # { radius: 0.3, height: 1.5, x: 0.0, y: 3.0, z: 0.5, roll: .0, pitch: 90.0 },
    # { radius: 0.3, height: 3.5, x: -1.0, y: 3.0, z: 0.0 },
    # { radius: 0.3, height: 3.5, x: 1.0, y: 5.0, z: 0.0 },
    # { radius: 0.3, height: 3.5, x: -1.0, y: 5.0, z: 0.0 },
  ]
