visualization: True #TODO:icluse this option in launch file
rope_length: 1.4

planning_type: "moving_obstacles" # static,moving_obstacles

calculate_new_path: True
timeout: 0.6

# env_mesh: "env-scene-ltu-experiment-corridor-narrow-easy"
# env_mesh: "env-scene-ltu-experiment-hole-inclined"
# env_mesh: "env-scene-ltu-experiment-corridor-narrow-narrow"
# env_mesh: "env-scene-ltu-experiment-tunnel2"
# env_mesh: "env-scene-ltu-experiment-small-hole"
# env_mesh: "env-scene-ltu-experiment-hole-wide"
env_mesh: "env-scene-ltu-experiment"

#Planning
val_check_resolution: 0.04
range: 1
use_mesh_improvement: True
goal_type: "simple" #simple,samplable,symmetrical,multiple_goals

use_ground_collision_check: False

#values:None, ob.PathLengthOptimizationObjective,balanced,obstacle_clearance
optimal_objective: { class: "None", threshold: 3 }

safety_distances: {
    #horizontal and vertical distance offset for drones
    drones_offsets: { horizontal: 0.05, vertical: 0.05 },

    #horizontal and vertical distance offset for lowest point of catenary
    lowest_point: 0.0,
  }

thickness: 0.2

# start and goal
start: { x: +0.0, y: 2.0, z: 0.75 }
goal: { x: +0.0, y: 6, z: 0.75 }

# Bounds of states
# All ANGLES are in DEGREES
bounds: {
    #x, y , z, yaw , drones_distance(% of L) , drones_angle
    low: [-1.5, 0.5, 0.3, -180.0, 0.3, -60.0],
    high: [1.5, 6.5, 2.0, 180.0, 0.95, 60.0],
  }

#planner algorithm
# planner_algorithm: "RRTstar"
planner_algorithm: "RRTConnect"
# planner_algorithm: "RRT"
# planner_algorithm: "InformedRRTstar"
# planner_algorithm: "PRM"
# planner_algorithm: "LBKPIECE"
# planner_algorithm: "KPIECE"

simplify_path: True
path_interpolation_points: 30
